name: bytebank
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  mask_text_input_formatter: ^2.3.0
  sqflite: ^2.0.2+1
  path: ^1.8.0
  uuid: ^3.0.6
  pie_chart: ^5.3.0
  http: ^0.13.4
  http_interceptor: ^1.0.2
  intl: ^0.17.0
  currency_text_input_formatter: ^2.1.5
  firebase_core: ^1.20.1
  firebase_crashlytics: ^2.8.7
  toast: ^0.3.0
  giff_dialog: ^1.0.1
  provider: ^6.0.3
  flutter_bloc: ^8.1.1
  i18n: ^3.4.1
  localstorage: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/giffs/error.gif
