name: bytebank
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  mask_text_input_formatter: ^2.3.0
  sqflite: ^2.0.2+1
  path: ^1.8.0
  uuid: ^3.0.6
  pie_chart: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
